version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/nodeproject
permissions:
  - object: /var/www/html/nodeproject
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
