version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Change this to your Node.js version
    commands:
      - npm install -g pm2

  pre_build:
    commands:
      - pm2 stop nodejs-app || true
      - pm2 delete nodejs-app || true
      - pm2 start app.js --name nodejs-app

  build:
    commands:
      - echo "Build started"

  post_build:
    commands:
      - pm2 save

